In [18]:
import numpy as np

Part1: Numpy 1D array operations


In [19]:
list1=[]
for i in range(1,21):
  list1.append(i)
print(list1)
array1=np.array(list1)
print(array1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [20]:
#Performing Mathematical Operations
#Sum
summation=np.sum(array1)
print(summation)
mean_val=np.mean(array1)
print(mean_val)
median_val=np.median(array1)
print(median_val)
std_val=np.std(array1)
print(std_val)

210
10.5
10.5
5.766281297335398


In [21]:
#Getting indices of the array
for i in range(len(array1)):
  if array1[i]>10:
    print(i)


10
11
12
13
14
15
16
17
18
19


Part2:2D-Array

In [22]:
arr=np.arange(1,17)
arr=arr.reshape(4,4)
print(arr)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [23]:
#Transpose of array
print(np.transpose(arr))

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


Part3: 3X3 Array

In [33]:
#Creating 1st Array
x1=np.random.randint(1,21,size=(3,3))
print(x1)
#Part a
#Creating 2nd Array
x2=np.random.randint(1,21,size=(3,3))
print(x2)

#Element wise Addition
Add_final=np.add(x1,x2)
print(f"The Addition of two matrices:\n",Add_final)

#Element wise Subtraction
Sub_final=np.subtract(x1,x2)
print(f"The Subtraction of two matrices:\n",Sub_final)

#Element wise Multiplication
mul_final=np.multiply(x1,x2)
print(f"The Multiplication of two matrices:\n",mul_final)

#Part b:
dot_final=np.dot(x1,x2)
print(f"The dot product of two matrices:\n",dot_final)

[[ 9  1 14]
 [ 6  1 20]
 [ 2  1 13]]
[[ 3  4 20]
 [15 19  3]
 [ 5 12  8]]
The Addition of two matrices:
 [[12  5 34]
 [21 20 23]
 [ 7 13 21]]
The Subtraction of two matrices:
 [[  6  -3  -6]
 [ -9 -18  17]
 [ -3 -11   5]]
The Multiplication of two matrices:
 [[ 27   4 280]
 [ 90  19  60]
 [ 10  12 104]]
The dot product of two matrices:
 [[112 223 295]
 [133 283 283]
 [ 86 183 147]]


Part4:Reshaping Array


In [24]:
#Creating 1D array
arr_new=np.arange(1,13)
print(arr_new)
print(arr_new.shape)

#Reshaping Array
arr_reshaped=arr_new.reshape(3,4)
print(arr_reshaped)

#Slicing First two rows
print(arr_reshaped[0:2,:])

#Slicing last two columns
print(arr_reshaped[:,2:4])

print(arr_reshaped[arr_reshaped>6])


[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[ 7  8  9 10 11 12]
